### ISSUE TITLE
None of the test benches work

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litevideo#2]
```
$ for DIR in $(find -name test -type d); do (cd $DIR; make); done
PYTHONPATH=../../../ python3 rgb2ycbcr_tb.py
Traceback (most recent call last):
  File "rgb2ycbcr_tb.py", line 52, in <module>
    tb = TB()
  File "rgb2ycbcr_tb.py", line 18, in __init__
    self.streamer.source.connect(self.rgb2ycbcr.sink, leave_out=["data"]),
TypeError: connect() got an unexpected keyword argument 'leave_out'
make: *** [rgb2ycbcr_tb] Error 1
PYTHONPATH=../../../ python3 core_tb.py
Traceback (most recent call last):
  File "core_tb.py", line 4, in <module>
    from litex.soc.interconnect import lasmi_bus
ImportError: cannot import name lasmi_bus
make: *** [core_tb] Error 1
The command "for DIR in $(find -name test -type d); do (cd $DIR; make); done" exited with 2.
```

**Comment by enjoy-digital** [comment]
It seems you are not using upstream code.
